# Use official Python image
FROM python:3.8

# Set working directory
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY requirements.txt .
RUN pip install -r requirements.txt


# Install spaCy model
RUN python -m spacy download en_core_web_sm

# Copy the current directory contents into the container at /backend
COPY . .

# Expose the Flask port
EXPOSE 5000            

# Run Flask app

# CMD ["python", "app.py"]
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]