# Use official Python image
FROM python:3.8

# Set working directory
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY requirements.txt .
RUN pip install -r requirements.txt


# Install spaCy model
RUN python -m spacy download en_core_web_sm

# Copy the current directory contents into the container at /backend
COPY . .

# Set Python path inside the container
ENV PYTHONPATH="/backend"

# Expose the Flask port
EXPOSE 5000            

# Run Flask app
CMD ["python", "-m","app"]
# CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
# CMD ["gunicorn", "-k", "eventlet", "-w", "1", "-b", "0.0.0.0:5000", "app:app"]